title: "ck1910's Blog"
description: software engineer born in Hanoi and lives in Singapore
url: https://www.dangchien.com 
author: ck1910
encoding: utf-8

twitter:
  username: dangchien87

social:
  name: Duong Dang Chien
  links:
    - https://twitter.com/dangchien87
    - https://github.com/DangChien
    - https://www.linkedin.com/in/duong-dang-chien-1b917b22/
    - https://stackoverflow.com/users/1277688/ck1910

google_analytics: UA-35823367-1
google_tag_manager: GTM-5KNFDCM

permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: rouge
excerpt_separator: <!--more-->
timezone: Asia/Singapore

sass:
  sass_dir: _sass
  style: compact

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-watch
  - jemoji

exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'README.md']
